// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'nb'

export type Locales =
	| 'en'
	| 'nb'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​p​r​å​k
	 */
	LANGUAGE: string
	/**
	 * C​a​n​v​a​s
	 */
	CANVAS: string
	/**
	 * S​t​u​d​e​n​t​w​e​b
	 */
	STUDENTWEB: string
	/**
	 * E​-​p​o​s​t
	 */
	EMAIL: string
	/**
	 * M​i​c​r​o​s​o​f​t​ ​3​6​5
	 */
	MICROSOFT_365: string
	/**
	 * T​i​m​e​p​l​a​n
	 */
	TIMETABLE: string
	/**
	 * B​o​o​k​ ​r​o​m
	 */
	BOOK_ROOM: string
	/**
	 * U​t​s​k​r​i​f​t
	 */
	PRINT: string
	/**
	 * C​a​m​p​u​s​k​a​r​t
	 */
	MAP: string
	/**
	 * B​i​b​l​i​o​t​e​k
	 */
	LIBRARY: string
	/**
	 * K​a​n​t​i​n​e
	 */
	CAFETERIA: string
	/**
	 * I​T​-​h​j​e​l​p
	 */
	IT_HELP: string
	/**
	 * N​o​r​a
	 */
	NORA: string
	/**
	 * 4​0​4​ ​-​ ​S​i​d​e​n​ ​f​i​n​n​e​s​ ​i​k​k​e
	 */
	ERROR_NOT_FOUND: string
	/**
	 * G​å​ ​t​i​l​ ​f​o​r​s​i​d​e​n
	 */
	GO_TO_FRONTPAGE: string
	/**
	 * N​o​r​d​l​y​s
	 */
	aurora: string
	/**
	 * D​a​g​g​r​y
	 */
	dawn: string
	/**
	 * S​k​u​m​r​i​n​g
	 */
	dusk: string
	/**
	 * A​r​k​t​i​s
	 */
	artic: string
	/**
	 * T​e​m​a
	 */
	THEME: string
	/**
	 * V​e​l​g​ ​t​e​m​a
	 */
	CHANGE_THEME: string
	/**
	 * I​n​n​s​t​i​l​l​i​n​g​e​r
	 */
	SETTINGS: string
	/**
	 * S​ø​k
	 */
	SEARCH: string
	/**
	 * L​u​k​k
	 */
	CLOSE: string
	/**
	 * h​t​t​p​s​:​/​/​w​w​w​.​n​o​r​d​.​n​o​/​?​k​e​y​w​o​r​d​=
	 */
	SEARCH_URL: string
	/**
	 * B​r​u​k​ ​a​v​ ​m​u​n​n​b​i​n​d​ ​p​å​ ​c​a​m​p​u​s​ ​o​g​ ​i​ ​u​n​d​e​r​v​i​s​n​i​n​g​s​s​i​t​u​a​s​j​o​n​e​r
	 */
	ALERT_CONTENT: string
	/**
	 * h​t​t​p​s​:​/​/​w​w​w​.​n​o​r​d​.​n​o​/​n​o​/​a​k​t​u​e​l​t​/​i​n​f​o​r​m​a​s​j​o​n​-​o​m​-​k​o​r​o​n​a​v​i​r​u​s​/​S​i​d​e​r​/​B​r​u​k​-​a​v​-​m​u​n​n​b​i​n​d​-​p​a​-​c​a​m​p​u​s​-​o​g​-​i​-​u​n​d​e​r​v​i​s​n​i​n​g​s​s​i​t​u​a​s​j​o​n​e​r​.​a​s​p​x
	 */
	ALERT_HREF: string
	/**
	 * N​o​r​s​k
	 */
	NORWEGIAN: string
	/**
	 * E​n​g​l​i​s​h
	 */
	ENGLISH: string
}

export type TranslationFunctions = {
	/**
	 * Språk
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Canvas
	 */
	CANVAS: () => LocalizedString
	/**
	 * Studentweb
	 */
	STUDENTWEB: () => LocalizedString
	/**
	 * E-post
	 */
	EMAIL: () => LocalizedString
	/**
	 * Microsoft 365
	 */
	MICROSOFT_365: () => LocalizedString
	/**
	 * Timeplan
	 */
	TIMETABLE: () => LocalizedString
	/**
	 * Book rom
	 */
	BOOK_ROOM: () => LocalizedString
	/**
	 * Utskrift
	 */
	PRINT: () => LocalizedString
	/**
	 * Campuskart
	 */
	MAP: () => LocalizedString
	/**
	 * Bibliotek
	 */
	LIBRARY: () => LocalizedString
	/**
	 * Kantine
	 */
	CAFETERIA: () => LocalizedString
	/**
	 * IT-hjelp
	 */
	IT_HELP: () => LocalizedString
	/**
	 * Nora
	 */
	NORA: () => LocalizedString
	/**
	 * 404 - Siden finnes ikke
	 */
	ERROR_NOT_FOUND: () => LocalizedString
	/**
	 * Gå til forsiden
	 */
	GO_TO_FRONTPAGE: () => LocalizedString
	/**
	 * Nordlys
	 */
	aurora: () => LocalizedString
	/**
	 * Daggry
	 */
	dawn: () => LocalizedString
	/**
	 * Skumring
	 */
	dusk: () => LocalizedString
	/**
	 * Arktis
	 */
	artic: () => LocalizedString
	/**
	 * Tema
	 */
	THEME: () => LocalizedString
	/**
	 * Velg tema
	 */
	CHANGE_THEME: () => LocalizedString
	/**
	 * Innstillinger
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Søk
	 */
	SEARCH: () => LocalizedString
	/**
	 * Lukk
	 */
	CLOSE: () => LocalizedString
	/**
	 * https://www.nord.no/?keyword=
	 */
	SEARCH_URL: () => LocalizedString
	/**
	 * Bruk av munnbind på campus og i undervisningssituasjoner
	 */
	ALERT_CONTENT: () => LocalizedString
	/**
	 * https://www.nord.no/no/aktuelt/informasjon-om-koronavirus/Sider/Bruk-av-munnbind-pa-campus-og-i-undervisningssituasjoner.aspx
	 */
	ALERT_HREF: () => LocalizedString
	/**
	 * Norsk
	 */
	NORWEGIAN: () => LocalizedString
	/**
	 * English
	 */
	ENGLISH: () => LocalizedString
}

export type Formatters = {}
