// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'nb'

export type Locales =
	| 'en'
	| 'nb'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​p​r​å​k
	 */
	LANGUAGE: string
	/**
	 * C​a​n​v​a​s
	 */
	CANVAS: string
	/**
	 * S​t​u​d​e​n​t​w​e​b
	 */
	STUDENTWEB: string
	/**
	 * E​-​p​o​s​t
	 */
	EMAIL: string
	/**
	 * M​i​c​r​o​s​o​f​t​ ​3​6​5
	 */
	MICROSOFT_365: string
	/**
	 * T​i​m​e​p​l​a​n
	 */
	TIMETABLE: string
	/**
	 * B​o​o​k​ ​r​o​m
	 */
	BOOK_ROOM: string
	/**
	 * U​t​s​k​r​i​f​t
	 */
	PRINT: string
	/**
	 * C​a​m​p​u​s​k​a​r​t
	 */
	MAP: string
	/**
	 * B​i​b​l​i​o​t​e​k
	 */
	LIBRARY: string
	/**
	 * K​a​n​t​i​n​e
	 */
	CAFETERIA: string
	/**
	 * I​T​-​h​j​e​l​p
	 */
	IT_HELP: string
	/**
	 * N​o​r​a
	 */
	NORA: string
	/**
	 * 4​0​4​ ​-​ ​S​i​d​e​n​ ​f​i​n​n​e​s​ ​i​k​k​e
	 */
	ERROR_NOT_FOUND: string
	/**
	 * G​å​ ​t​i​l​ ​f​o​r​s​i​d​e​n
	 */
	GO_TO_FRONTPAGE: string
	/**
	 * N​o​r​d​l​y​s
	 */
	aurora: string
	/**
	 * D​a​g​g​r​y
	 */
	dawn: string
	/**
	 * S​k​u​m​r​i​n​g
	 */
	dusk: string
	/**
	 * A​r​k​t​i​s
	 */
	artic: string
	/**
	 * T​e​m​a
	 */
	THEME: string
	/**
	 * V​e​l​g​ ​t​e​m​a
	 */
	CHANGE_THEME: string
	/**
	 * I​n​n​s​t​i​l​l​i​n​g​e​r
	 */
	SETTINGS: string
	/**
	 * S​ø​k
	 */
	SEARCH: string
	/**
	 * L​u​k​k
	 */
	CLOSE: string
	/**
	 * h​t​t​p​s​:​/​/​n​o​r​a​-​t​e​s​t​.​n​o​r​d​.​n​o​/​?​c​o​n​s​e​n​t​=​T​r​u​e​&​q​=
	 */
	SEARCH_URL: string
	/**
	 * B​r​u​k​ ​a​v​ ​m​u​n​n​b​i​n​d​ ​p​å​ ​c​a​m​p​u​s​ ​o​g​ ​i​ ​u​n​d​e​r​v​i​s​n​i​n​g​s​s​i​t​u​a​s​j​o​n​e​r
	 */
	ALERT_CONTENT: string
	/**
	 * h​t​t​p​s​:​/​/​w​w​w​.​n​o​r​d​.​n​o​/​n​o​/​a​k​t​u​e​l​t​/​i​n​f​o​r​m​a​s​j​o​n​-​o​m​-​k​o​r​o​n​a​v​i​r​u​s​/​S​i​d​e​r​/​B​r​u​k​-​a​v​-​m​u​n​n​b​i​n​d​-​p​a​-​c​a​m​p​u​s​-​o​g​-​i​-​u​n​d​e​r​v​i​s​n​i​n​g​s​s​i​t​u​a​s​j​o​n​e​r​.​a​s​p​x
	 */
	ALERT_HREF: string
	/**
	 * N​o​r​s​k
	 */
	NORWEGIAN: string
	/**
	 * E​n​g​l​i​s​h
	 */
	ENGLISH: string
	/**
	 * O​m​ ​n​e​t​t​s​i​d​e​n
	 */
	ABOUT_HEADING: string
	/**
	 * H​v​a​ ​e​r​ ​M​i​t​t​ ​N​o​r​d​?
	 */
	ABOUT_THE_SITE_HEADING: string
	/**
	 * M​i​t​t​ ​N​o​r​d​ ​e​r​ ​e​n​ ​s​i​d​e​ ​f​o​r​ ​s​t​u​d​e​n​t​e​r​ ​v​e​d​ ​N​o​r​d​ ​u​n​i​v​e​r​s​i​t​e​t​.
	 */
	ABOUT_THE_SITE_P1: string
	/**
	 * S​i​d​e​n​ ​s​a​m​l​e​r​ ​a​l​t​ ​d​u​ ​t​r​e​n​g​e​r​ ​p​å​ ​e​t​t​ ​s​t​e​d​.​ ​N​o​e​n​ ​l​e​n​k​e​r​ ​v​i​l​ ​d​u​ ​t​r​e​n​g​e​ ​d​a​g​l​i​g​,​ ​a​n​d​r​e​ ​k​u​n​ ​e​n​ ​g​a​n​g​ ​i​ ​s​k​u​d​d​å​r​e​t​.​ ​�​�
	 */
	ABOUT_THE_SITE_P2: string
	/**
	 * F​o​l​k​a​ ​b​a​k
	 */
	ABOUT_THE_PEOPLE_HEADING: string
	/**
	 * M​i​t​t​ ​N​o​r​d​ ​e​r​ ​l​a​g​e​t​ ​a​v​ 
	 */
	ABOUT_THE_PEOPLE_P1: string
	/**
	 * .​ ​M​o​r​t​e​n​ ​e​r​ ​o​v​e​r​ ​g​j​e​n​n​o​m​s​n​i​t​t​l​i​g​ ​g​l​a​d​ ​i​ ​s​u​r​e​ ​o​r​d​s​p​i​l​l​,​ ​v​e​l​f​e​r​m​e​n​t​e​r​t​e​ ​s​u​r​d​e​i​g​s​b​r​ø​d​ ​o​g​ ​g​o​d​e​ ​b​r​u​k​e​r​o​p​p​l​e​v​e​l​s​e​r​.​ ​N​å​ ​f​o​r​ ​t​i​d​e​n​ ​l​e​v​e​r​ ​h​a​n​ ​a​v​ ​å​ ​l​a​g​e​n​ ​l​e​v​e​r​ ​h​a​n​ ​a​v​ ​å​ ​l​a​g​e​ 
	 */
	ABOUT_THE_PEOPLE_P2: string
	/**
	 * j​o​u​r​n​a​l​s​y​s​t​e​m​e​r​ ​f​o​r​ ​p​s​y​k​o​l​o​g​e​r
	 */
	ABOUT_THE_PEOPLE_P3: string
	/**
	 * N​o​e​ ​p​å​ ​h​j​e​r​t​e​t​?
	 */
	ABOUT_CONTACT_US_HEADING: string
	/**
	 * H​a​r​ ​d​u​ ​t​i​p​s​,​ ​r​i​s​ ​e​l​l​e​r​ ​r​o​s​?​ ​S​e​n​d​ ​e​n​ ​e​-​p​o​s​t​ ​t​i​l
	 */
	ABOUT_CONTACT_US_P1: string
	/**
	 * e​l​l​e​r
	 */
	ABOUT_CONTACT_US_P2: string
	/**
	 * s​j​e​k​k​ ​u​t​ ​k​o​d​e​n​ ​p​å​ ​G​i​t​h​u​b
	 */
	ABOUT_CONTACT_US_P3: string
}

export type TranslationFunctions = {
	/**
	 * Språk
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Canvas
	 */
	CANVAS: () => LocalizedString
	/**
	 * Studentweb
	 */
	STUDENTWEB: () => LocalizedString
	/**
	 * E-post
	 */
	EMAIL: () => LocalizedString
	/**
	 * Microsoft 365
	 */
	MICROSOFT_365: () => LocalizedString
	/**
	 * Timeplan
	 */
	TIMETABLE: () => LocalizedString
	/**
	 * Book rom
	 */
	BOOK_ROOM: () => LocalizedString
	/**
	 * Utskrift
	 */
	PRINT: () => LocalizedString
	/**
	 * Campuskart
	 */
	MAP: () => LocalizedString
	/**
	 * Bibliotek
	 */
	LIBRARY: () => LocalizedString
	/**
	 * Kantine
	 */
	CAFETERIA: () => LocalizedString
	/**
	 * IT-hjelp
	 */
	IT_HELP: () => LocalizedString
	/**
	 * Nora
	 */
	NORA: () => LocalizedString
	/**
	 * 404 - Siden finnes ikke
	 */
	ERROR_NOT_FOUND: () => LocalizedString
	/**
	 * Gå til forsiden
	 */
	GO_TO_FRONTPAGE: () => LocalizedString
	/**
	 * Nordlys
	 */
	aurora: () => LocalizedString
	/**
	 * Daggry
	 */
	dawn: () => LocalizedString
	/**
	 * Skumring
	 */
	dusk: () => LocalizedString
	/**
	 * Arktis
	 */
	artic: () => LocalizedString
	/**
	 * Tema
	 */
	THEME: () => LocalizedString
	/**
	 * Velg tema
	 */
	CHANGE_THEME: () => LocalizedString
	/**
	 * Innstillinger
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Søk
	 */
	SEARCH: () => LocalizedString
	/**
	 * Lukk
	 */
	CLOSE: () => LocalizedString
	/**
	 * https://nora-test.nord.no/?consent=True&q=
	 */
	SEARCH_URL: () => LocalizedString
	/**
	 * Bruk av munnbind på campus og i undervisningssituasjoner
	 */
	ALERT_CONTENT: () => LocalizedString
	/**
	 * https://www.nord.no/no/aktuelt/informasjon-om-koronavirus/Sider/Bruk-av-munnbind-pa-campus-og-i-undervisningssituasjoner.aspx
	 */
	ALERT_HREF: () => LocalizedString
	/**
	 * Norsk
	 */
	NORWEGIAN: () => LocalizedString
	/**
	 * English
	 */
	ENGLISH: () => LocalizedString
	/**
	 * Om nettsiden
	 */
	ABOUT_HEADING: () => LocalizedString
	/**
	 * Hva er Mitt Nord?
	 */
	ABOUT_THE_SITE_HEADING: () => LocalizedString
	/**
	 * Mitt Nord er en side for studenter ved Nord universitet.
	 */
	ABOUT_THE_SITE_P1: () => LocalizedString
	/**
	 * Siden samler alt du trenger på ett sted. Noen lenker vil du trenge daglig, andre kun en gang i skuddåret. 🤷
	 */
	ABOUT_THE_SITE_P2: () => LocalizedString
	/**
	 * Folka bak
	 */
	ABOUT_THE_PEOPLE_HEADING: () => LocalizedString
	/**
	 * Mitt Nord er laget av 
	 */
	ABOUT_THE_PEOPLE_P1: () => LocalizedString
	/**
	 * . Morten er over gjennomsnittlig glad i sure ordspill, velfermenterte surdeigsbrød og gode brukeropplevelser. Nå for tiden lever han av å lagen lever han av å lage 
	 */
	ABOUT_THE_PEOPLE_P2: () => LocalizedString
	/**
	 * journalsystemer for psykologer
	 */
	ABOUT_THE_PEOPLE_P3: () => LocalizedString
	/**
	 * Noe på hjertet?
	 */
	ABOUT_CONTACT_US_HEADING: () => LocalizedString
	/**
	 * Har du tips, ris eller ros? Send en e-post til
	 */
	ABOUT_CONTACT_US_P1: () => LocalizedString
	/**
	 * eller
	 */
	ABOUT_CONTACT_US_P2: () => LocalizedString
	/**
	 * sjekk ut koden på Github
	 */
	ABOUT_CONTACT_US_P3: () => LocalizedString
}

export type Formatters = {}
